### ISSUE TITLE
required inputs

### ISSUE THREAD

**Issue by dilekozkan** [sergivalverde/lesion-toads#1]
Hello all, 

I have read the article. I am confused since it is written that  .. the variability of lesion intensity on T1-weighted image does not deteriorate the segmentation of lesions and ... In addition to this multichannel weighting scheme, we further enhance the clustering model using the approach described by Roy et al. (2008) to particularly improve accuracy on (MPRAGE) T1-weighted images.

We have 3D T1 in a few patients. If you use the 3D T1 images for co-registration or gray/white matter segmentation, I could try to use the 3D MRI scout (3D calibration scans, blurry image with T1 contrast displayed as a separate series) instead of the 3D T1. **As far as I understood you don't use 3D T1 just for registration or gray/white matter segmentation. Am I right?** 

2)How about reliable range, can we use other 3d T1 (vibe etc)?

**Comment by sergivalverde** [comment]
Hi @dilekozkan 

Could you please help me with the article? Which article do you refer?

**Comment by dilekozkan** [comment]
Hello, 

thank you for your quick response. Article: A topology-preserving approach to the segmentation of brain images with multiple sclerosis lesions

**Comment by sergivalverde** [comment]
We are not the authors of the article.  So we cannot help with this.

We just used their software with the nipype interface.  With default options. And using original images as they were (3D I’f available etc…)
________________________________
De: Dilek Ozkan ***@***.***>
Enviado: Thursday, August 25, 2022 2:02:16 PM
Para: sergivalverde/lesion-toads ***@***.***>
Cc: Sergi Valverde ***@***.***>; Comment ***@***.***>
Asunto: Re: [sergivalverde/lesion-toads] required inputs (Issue #1)


Hello,

thank you for your quick response. Article: A topology-preserving approach to the segmentation of brain images with multiple sclerosis lesions
